modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
issueTrackerURL="https://github.com/MCTeamPotato/Better-End-Potato-Edition/issues"

[[mods]]
modId="betterendforge"
version="${file.jarVersion}}"
displayName="Better End Potato Edition"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-end-potato-edition"
logoFile="icon.png"
credits="Main Author: SomeoneElse - Former Authors of the port: Beethoven92, Vemerion. All the artistic rights and credits, except for Forge-specific portions of code, go to the original authors of the BetterEnd mod for the Fabric mod loader"
authors="TeamPotato"
description='''
This mod adds new content to the end dimension that vastly improves and expands your end game. Now in parity with Fabric
'''

[[dependencies.betterendforge]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.betterendforge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
